blog/urls.py
from django import urls
from django.urls import re_path, path, include
from django.conf import settings
from django.conf.urls.static import static

from .import views
app_name='blog'

urlpatterns = [
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    path('a', views.index2, name='index2'),
    re_path(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>', views.CategoryView.as_view(), name='category'),
    path("tag/<int:pk>", views.TagView.as_view(), name='tag'),
    path("search/", views.search, name='search'),
    path("about/", views.AboutView.as_view(), name='about'),

]



blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

from ckeditor_uploader.fields import RichTextUploadingField
from mdeditor.fields import MDTextField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    

class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name
    

class Post(models.Model):
    '''文章'''
    
    # 文章标题
    title = models.CharField('标题',max_length=70)
    
    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    # body = RichTextUploadingField(config_name='default')
    # body = models.TextField()
    body = MDTextField()

    # 在models里添加picture字段
    # upload_to 将图片上传到static文件下的images
    picture = models.ImageField(upload_to='media',blank=True)
    
    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField('创建时间',default=timezone.now)
    modified_time = models.DateTimeField('修改时间')
    
    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200,blank=True)
    
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag,blank=True)
    
    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    views = models.PositiveIntegerField(default=0, editable=False)

    top_symbol = models.IntegerField(default=0,blank=True)

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-top_symbol','-created_time']
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])


class visitCount(models.Model):

    count = models.PositiveIntegerField(default=0, editable=True)
    print('count call:',count)

    def __str__(self):
        return str(self.count)

    def save(self,*args, **kwargs):
        self.count += 1
        super().save(*args, **kwargs)
        return self.count

    # def increase_views(self):
    #     self.count += 1
    #     self.save(update_fields=['count'])
    #     return self.count

class viewIP(models.Model):
    ip = models.CharField('访问者IP',max_length=500)
    view_time = models.DateTimeField('访问时间', default=timezone.now)




    

comments/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Comment(models.Model):

    name = models.CharField('名字',max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址',blank=True)
    text = models.TextField('内容')
    created_time = models.TimeField('创建时间',default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章',on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}:{}'.format(self.name, self.text[:20])

    # def get_absolute_url(self):
    #     return reverse("Comment_detail", kwargs={"pk": self.pk})

blog/views.py
from django.db.models.query_utils import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.shortcuts import HttpResponse
from django.utils.text import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.contrib import messages
from django.utils import timezone
from datetime import datetime, timedelta

import markdown
from markdown.extensions.toc import TocExtension
import re

from .models import *

# Create your views here.

def stat_IP(request):

    recount_interval = 3600   # 单个IP重新计算浏览量的间隔时间
    del_interval = 7200       # 清除表中旧IP的间隔时间
    now_time = timezone.now()
    count = 0

    if 'HTTP_X_FORWARDED_FOR' in request.META:        # 获取用户真实IP地址
        user_ip = request.META['HTTP_X_FORWARDED_FOR']
    else:
        user_ip = request.META['REMOTE_ADDR']
    
    print('user_ip',user_ip)


    if viewIP.objects.filter(ip=user_ip).exists():             # 检查目前浏览的IP是否在表中存在
        obj = viewIP.objects.filter(ip=user_ip).first()
        old_time = viewIP.objects.filter(ip=user_ip).values('view_time')[0]['view_time']
        print(old_time)
        obj.view_time = now_time
        obj.save()
        if (now_time - old_time).seconds > recount_interval:   # IP存在，更新访问时间; 若距上次访问超过一小时，增加访问量                                                 # I
            count = 1
    else:                                                      # IP不存在，增加记录，增加访问量
        count = 1
        viewIP.objects.create(ip=user_ip,view_time=now_time)


    last_time = viewIP.objects.all().order_by('view_time').values('view_time')[0]['view_time']
    if (now_time - last_time).seconds > del_interval:
        due_time = now_time - timedelta(seconds=recount_interval)
        viewIP.objects.filter(view_time__lt=due_time).delete()

    return count


def get_count(request):
    visit_Count = visitCount.objects.get(id=1)
    # co = visit_Count.count+1
    # visit_Count.count = co
    

    # return visit_Count.save()
    # return visit_Count.increase_counts
    return render(request, 'blog/index.html',{'visit_Count':visit_Count})

# def base(request,url):
#     post_list = Post.objects.all().order_by('-created_time')
#     return render(request,url,{'post_list':post_list,'count':get_count()})


def index2(request):
    return render(request, 'blog/index2.html', context={
        'title': '我的博客首页',
        'welcome': '欢迎访问我的博客首页'
        })

def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    # print(post_list)

    paginator = Paginator(post_list, 5) # 每页显示 25 个联系人

    page = request.GET.get('page')

    # 旧版Django
    # try:
    #     posts = paginator.page(page)
    # except PageNotAnInteger:
    #     # 如果用户请求的页码号不是整数，显示第一页
    #     posts = paginator.page(1)
    # except EmptyPage:
    #     # 如果用户请求的页码号超过了最大页码号，显示最后一页
    #     posts = paginator.page(paginator.num_pages)

    posts = paginator.get_page(page)

    return render(request,'blog/index.html',{'posts': posts})

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 5

def detail(request,pk):
    post = get_object_or_404(Post,pk=pk)
    # post.body = markdown.markdown(post.body,
    #                               extensions=[
    #                                   'markdown.extensions.extra',
    #                                   'markdown.extensions.codehilite',
    #                                   'markdown.extensions.toc',
    #                               ])

    post.increase_views()

    md = markdown.Markdown(
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(slugify=slugify),

        ]
    )
    post.body = md.convert(post.body)

    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>',md.toc,re.S)
    post.toc = m.group(1) if m is not None else ''

    # post_list = Post.objects.all().order_by('-created_time')[:5]

    return render(request, 'blog/detail.html',{'post':post})

# def archive(request,year,month):
#     post_list = Post.objects.filter(
#         created_time__year=year,
#         created_time__month=month
#     ).order_by('-created_time')
#     return render(request,'blog/index.html',{'post_list':post_list})

class ArchiveView(ListView):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):

        return super(ArchiveView,self).get_queryset().filter(created_time__year=self.kwargs.get('year'),created_time__month=self.kwargs.get('month'))

# def category(request,pk):
#     cate = get_object_or_404(Category,pk=pk)
#     post_list = Post.objects.filter(
#         category=cate
#     ).order_by('-created_time')
#     return render(request,'blog/index.html',{'post_list':post_list})

class CategoryView(ListView):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        cate = get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)

# def tag(request,pk):
#     t = get_object_or_404(Tag,pk=pk)
#     post_list = Post.objects.filter(
#         tags=t
#     ).order_by('-created_time')
#     return render(request,'blog/index.html',{'post_list':post_list})

class TagView(ListView):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "posts"
    paginate_by = 5

    def get_queryset(self):
        t = get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tags=t)


def search(request):
    q = request.GET.get('q')

    if not q:
        error_msg = "请输入关键词"
        messages.add_message(request,messages.ERROR,error_msg,extra_tags='danger')
        return redirect('blog:index')

    posts = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request,'blog/index.html',{'posts':posts})

class AboutView(ListView):
    model = Post
    template_name = "blog/about.html"
    context_object_name = "about_post"

    def get_queryset(self):
        return super(AboutView,self).get_queryset().filter(title="about")

templates/blog/about.html
{% extends 'blog/base.html' %}
{% load comments_extras %}
 
 {% block main %}

            {% for post in about_post %}
                <article class="post post-1">
                    {% comment %} <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header> {% endcomment %}
                    <div class="entry-content clearfix">
                    {{ post.body|safe|linebreaksbr }}

                    </div>
                </article>

            {% endfor %}
                {% comment %} <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>

                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}

                    {% block comment %}
                    {% if failMark %}
                        {% show_comment_form post form %}
                    {% else %}
                        {% show_comment_form post %}
                    {% endif %}
                    {% endblock comment %}
                    
                    <div class="comment-list-panel">
                        {% show_comments post %}
                    </div>
                </section> {% endcomment %}
{% endblock main %}
{% block toc %}
    {% if post.toc %}
 
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <div class="toc">
                    <ul>
                       {{ post.toc|safe }}
                    </ul>
                    </div>
                </div>
    {% endif %}

 
{% endblock toc %}
     

templates/blog/base.html
{% load static %}
{% load blog_extras %}
 
<!DOCTYPE html>
<html>
<head>
 <title>DragC Blog</title>
 
 <!-- meta -->
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 
 <!-- css -->
 {% comment %} <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}" > {% endcomment %}
 <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
 <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="external nofollow" rel="external nofollow" rel="external nofollow" >
 <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}" rel="external nofollow" rel="external nofollow" >
 <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}" rel="external nofollow" >
 <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">
 
 <!-- js -->
 {% comment %} <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
 <script src="{% static 'blog/js/bootstrap.min.js' %}"></script> {% endcomment %}
 <script src="https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js"></script>
 <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <script src="{% static 'blog/js/pace.min.js' %}"></script>
 <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>

 <!-- 百度统计 -->
 <script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?242b419f7428f86c443922924c9e6fd4";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>


 <!-- code highlight -->
 <style>

    body {
        background-image:url({% static 'blog/img/bg.jpeg' %});
        background-attachment: fixed;
        background-size: 100% 100%;
    }

    .codehilite {
      padding: 0;
    }

    /* for block of numbers */
    .hljs-ln-numbers {
      -webkit-touch-callout: none;
      -webkit-user-select: none;
      -khtml-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;

      text-align: center;
      color: #ccc;
      border-right: 1px solid #CCC;
      vertical-align: top;
      padding-right: 5px;
    }

    .hljs-ln-n {
      width: 30px;
    }

    /* for block of code */
    .hljs-ln .hljs-ln-code {
      padding-left: 10px;
      white-space: pre;
    }

    .outer{
        margin:0 auto;
        background:rgba(255,255,255,0.9);
    }

    @media screen and (min-width: 1481px){
        .outer {width:80%;}
    }

    @media screen and (max-width: 1480px){
        .outer {width:1170px;}
    }

    @media screen and (max-width: 1200px){
        .outer {width:90%;}
    }

    @media screen and (max-width: 1110px){
        .outer {width:990px;}
    }

    @media screen and (max-width: 990px){
        .outer {width:100%;}
    }

  </style>



</head>

<body>

<div class="outer">

<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>灵感小筑</b> DragC</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            {% top_cates %}
                            <li class="cl-effect-11"><a href={% url 'blog:about' %} data-hover="关于">关于</a></li>

                        {% comment %} <li class="cl-effect-14"> 
                        <a href="#"> 
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                        </li>
                        </a> {% endcomment %}

                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>

{% comment %} {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %} {% endcomment %}

</div>
<div class="copyrights">&copy 2021 - DragC的博客 - 部署于树莓派</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">

            {% block main %}{% endblock main %}

            </main>
            <aside class="col-md-4">
                {% block toc %}{% endblock toc %}

                <div class="content" style="width: 100%; background-color:#FFFFFF">

                <div class="content" style="width: 90%; margin-left: 5%; margin-right: 5%;">

                {% show_recent_posts %}
                {% show_archives %}
                {% show_categories %}
                {% show_tags %}

                </div>
                </div>


                {% comment %} <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div> {% endcomment %}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2021 - DragC的博客 - 部署于树莓派
                </p>
                {% get_counts %}
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul class="">
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            {% top_cates %}
            <li><a href={% url 'blog:about' %}>关于</a></li>
        </ul>
    </nav>
</div>

</div>

<script src="{% static 'blog/js/script.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

</body>
</html>

templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load comments_extras %}
 
 {% block main %}

                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="#comment-area">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                    {{ post.body|safe|linebreaksbr }}

                    </div>
                </article>
                <section class="comment-area" id="comment-area">
                    <hr>
                    <h3>发表评论</h3>

                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}

                    {% block comment %}
                    {% if failMark %}
                        {% show_comment_form post form %}
                    {% else %}
                        {% show_comment_form post %}
                    {% endif %}
                    {% endblock comment %}
                    
                    <div class="comment-list-panel">
                        {% show_comments post %}
                    </div>
                </section>
{% endblock main %}
{% block toc %}
    {% if post.toc %}
 
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    <div class="toc">
                    <ul>
                       {{ post.toc|safe }}
                    </ul>
                    </div>
                </div>
    {% endif %}

 
{% endblock toc %}
     

templates/blog/index2.html
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <title>{{ title }}</title>
</head>
<body>
 <h1>aaaa{{ post_list }}</h1>
</body>
</html>